version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: dotnet_api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: nextjs_app
    environment:
      - NEXT_PUBLIC_BASE_URL=http://dotnet_api:8000
    ports:
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
