version: "3.8"

services:
  api:
    image: kontotestowedominik/hackyeah:v2
    container_name: dotnet_api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: kontotestowedominik/hackyeah:v1
    container_name: nextjs_app
    environment:
      - NEXT_PUBLIC_BASE_URL=http://dotnet_api:8000/api
    ports:
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
